"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Camera, Check, ChevronRight, Clock3, Dumbbell, Mail, MapPin, Menu, Phone, Play, Quote, X } from "lucide-react";
import type { GymDemoData, GymSection } from "@/lib/demo-data";

const fallbackHero = "/trainers/imageye___-_imgi_219_young-muscular-man-exercising-with-trx-straps.jpg";
const section = (demo: GymDemoData, key: GymSection["key"]) => demo.sections.find((item) => item.key === key && item.visible);
const digits = (value?: string) => value?.replace(/[^0-9+]/g, "") ?? "";

function Brand({ demo }: { demo: GymDemoData }) {
  const words = demo.businessName.trim().split(/\s+/); const first = words[0]; const rest = words.slice(1).join(" ");
  return <span className="public-logo">{demo.logo ? <span><Image src={demo.logo} alt={`${demo.businessName} logo`} fill sizes="40px" unoptimized /></span> : <span><Dumbbell /></span>}<b>{first}<small>{rest || "FITNESS"}</small></b></span>;
}

export function PublicSite({ demo }: { demo: GymDemoData }) {
  const [nav, setNav] = useState(false); const [sent, setSent] = useState(false);
  const about = section(demo, "about"); const services = section(demo, "services"); const features = section(demo, "features"); const testimonials = section(demo, "testimonials"); const cta = section(demo, "cta"); const faq = section(demo, "faq"); const gallery = demo.gallery;
  const phone = digits(demo.phone); const whatsapp = digits(demo.whatsapp); const location = [demo.address, demo.area, demo.city, demo.state].filter(Boolean).join(", ");
  const navItems = [{ label: "About", enabled: Boolean(about) }, { label: "Membership", enabled: Boolean(services) }, { label: "Classes", enabled: Boolean(services) }, { label: "Gallery", enabled: gallery.length > 0 }, { label: "Stories", enabled: Boolean(testimonials) }, { label: "Contact", enabled: true }].filter((item) => item.enabled);
  return <main className="public-site" style={{ "--lime": demo.primaryColor, "--gym-brand-dark": demo.secondaryColor } as React.CSSProperties}>
    <nav className="public-nav"><Link href={`/${demo.slug}`} aria-label={`${demo.businessName} home`}><Brand demo={demo} /></Link><div className={nav ? "nav-links open" : "nav-links"}>{navItems.map(({ label }) => <a onClick={() => setNav(false)} href={`#${label.toLowerCase()}`} key={label}>{label}</a>)}<Link className="nav-login" href="/login">Owner login</Link></div><div className="nav-cta">{whatsapp && <a href={`https://wa.me/${whatsapp.replace("+", "")}`} target="_blank" rel="noreferrer" className="btn public-outline">Book free trial</a>}<button aria-label="Toggle navigation" className="public-menu" onClick={() => setNav(!nav)}>{nav ? <X /> : <Menu />}</button></div></nav>
    <section className="public-hero"><div className="hero-bg"><Image src={demo.heroImage ?? gallery[0] ?? fallbackHero} alt={`${demo.businessName} training experience`} fill priority sizes="100vw" className="object-cover" unoptimized /></div><div className="hero-overlay" /><div className="hero-content"><span className="hero-kicker"><i /> {demo.city ? `${demo.city.toUpperCase()} FITNESS DESTINATION` : "TRAIN WITH PURPOSE"}</span><h1>{demo.tagline.split(" ").slice(0, 3).join(" ")}<br/><em>{demo.tagline.split(" ").slice(3).join(" ") || "START TODAY"}</em></h1><p>{demo.shortDescription}</p><div>{services && <a className="btn hero-primary" href="#membership">Explore training <ArrowRight /></a>}<a className="play-link" href="#about"><i><Play fill="currentColor" /></i>Discover our approach</a></div></div><div className="hero-side"><span>{demo.businessName.toUpperCase()}</span><i /><span>COACHING · COMMUNITY · PROGRESS</span></div>{features?.items.length ? <div className="hero-stats">{features.items.slice(0, 4).map((item, index) => <div key={`${item.title}-${index}`}><b>{String(index + 1).padStart(2, "0")}</b><span>{item.title}</span></div>)}</div> : null}</section>
    {about && <section className="public-intro" id="about"><div><span className="section-index">01 — ABOUT {demo.businessName.toUpperCase()}</span><h2>{about.title ?? "NOT JUST A GYM."}<br/><em>{about.subtitle ?? "A STANDARD."}</em></h2></div><div><p>{about.text}</p>{features?.items.length ? <div className="public-features">{features.items.slice(0, 3).map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div> : null}</div></section>}
    {services?.items.length ? <section className="public-plans" id="membership"><header><div><span className="section-index">02 — TRAINING OPTIONS</span><h2>{services.title ?? "INVEST IN YOUR"}<br/><em>{services.subtitle ?? "STRONGEST YEAR."}</em></h2></div><p>{services.text ?? "Choose the right starting point for your fitness goals."}</p></header><div className="public-price-grid">{services.items.slice(0, 4).map((item, index) => <article className={index === 1 ? "featured" : ""} key={`${item.title}-${index}`}>{index === 1 && <span className="best">POPULAR</span>}<small>{String(index + 1).padStart(2, "0")}</small><h3>{item.title}</h3>{item.price && <div className="public-price"><b>{item.price}</b><span>{item.duration ? `/ ${item.duration}` : ""}</span></div>}<p>{item.description}</p>{item.features?.length ? <ul>{item.features.map((feature) => <li key={feature}><Check />{feature}</li>)}</ul> : null}<a href="#trial">Get started <ArrowRight /></a></article>)}</div></section> : null}
    {gallery.length ? <section className="public-trainers" id="gallery"><div className="public-section-head"><div><span className="section-index">03 — THE EXPERIENCE</span><h2>SEE WHERE<br/><em>YOU’LL TRAIN.</em></h2></div><p>A closer look at {demo.businessName}.</p></div><div className="public-trainer-grid">{gallery.slice(0, 4).map((image, index) => <article key={`${image}-${index}`}><div><Image src={image} alt={`${demo.businessName} gallery ${index + 1}`} fill sizes="(max-width: 700px) 50vw, 25vw" className="object-cover" unoptimized/><span>0{index + 1}</span></div><h3>{demo.businessName}</h3><p>Training environment</p></article>)}</div></section> : null}
    {services?.items.length ? <section className="classes-section" id="classes"><div className="public-section-head"><div><span className="section-index">04 — CLASSES</span><h2>FIND YOUR<br/><em>FIRE.</em></h2></div><p>Focused sessions built around real goals.</p></div><div className="class-strips">{services.items.slice(0, 5).map((item, index) => <article key={`${item.title}-class`}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><div><b>{item.duration ?? "FLEXIBLE"}</b><small>{item.description ?? "Coached session"}</small></div><a href="#trial" aria-label={`Ask about ${item.title}`}><ChevronRight /></a></article>)}</div></section> : null}
    {testimonials?.items.length ? <section className="transformation-public" id="stories"><div className="transform-photo"><Image src={testimonials.items[0].image ?? gallery[0] ?? fallbackHero} alt={`${demo.businessName} member story`} fill sizes="50vw" className="object-cover" unoptimized/><div className="quote-mark"><Quote /></div></div><div><span className="section-index">05 — REAL EXPERIENCES</span><h2>“{testimonials.items[0].quote ?? testimonials.items[0].description ?? "CONSISTENCY CHANGED EVERYTHING."}”</h2><p>{testimonials.text ?? "Real members building strength, confidence and better habits."}</p><span className="member-name">{(testimonials.items[0].name ?? testimonials.items[0].title).toUpperCase()} · {demo.businessName.toUpperCase()}</span></div></section> : null}
    {faq?.items.length ? <section className="public-intro" id="faq"><div><span className="section-index">06 — FAQ</span><h2>{faq.title ?? "QUESTIONS,"}<br/><em>ANSWERED.</em></h2></div><div className="public-features">{faq.items.map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section> : null}
    <section className="trial-section" id="trial"><div><span className="section-index">07 — START TODAY</span><h2>{cta?.title ?? "YOUR FIRST SESSION"}<br/><em>{cta?.subtitle ?? "STARTS HERE."}</em></h2><p>{cta?.text ?? demo.shortDescription}</p><div className="contact-points">{demo.phone && <a href={`tel:${phone}`}><Phone />{demo.phone}</a>}{location && <a href={demo.googleMapsUrl ?? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`} target="_blank" rel="noreferrer"><MapPin />{location}</a>}<span><Clock3 />Contact us for current timings</span></div></div><form onSubmit={(event) => { event.preventDefault(); setSent(true); }}>{sent ? <div className="form-success"><Check /><h3>Trial request ready!</h3><p>Contact {demo.businessName} to confirm your preferred slot.</p>{whatsapp && <a className="btn hero-primary" href={`https://wa.me/${whatsapp.replace("+", "")}?text=${encodeURIComponent(`Hi ${demo.businessName}, I would like to book a trial session.`)}`} target="_blank" rel="noreferrer">Continue on WhatsApp</a>}<button type="button" onClick={() => setSent(false)}>Start again</button></div> : <><label>Your name<input required placeholder="Full name" /></label><label>Phone number<input required inputMode="tel" placeholder="Mobile number" /></label><label>Fitness goal<select required defaultValue=""><option value="" disabled>Select your goal</option><option>Weight loss</option><option>Muscle building</option><option>General fitness</option><option>Strength</option></select></label><label>Preferred time<select><option>Morning</option><option>Evening</option></select></label><button>Book my free trial <ArrowRight /></button><small>No payment required. Contact details remain in this page session.</small></>}</form></section>
    <footer id="contact"><Link href={`/${demo.slug}`}><Brand demo={demo} /></Link><p>{demo.tagline}<br/>{demo.city ? `${demo.city}, ${demo.state ?? "India"}` : "Fitness built around you."}</p><div><b>Explore</b>{services && <a href="#membership">Training</a>}<a href="#about">About</a>{gallery.length ? <a href="#gallery">Gallery</a> : null}</div><div><b>Contact</b>{demo.phone && <a href={`tel:${phone}`}>{demo.phone}</a>}{demo.email && <a href={`mailto:${demo.email}`}>{demo.email}</a>}{whatsapp && <a href={`https://wa.me/${whatsapp.replace("+", "")}`}>WhatsApp</a>}</div><div className="social">{demo.instagramUrl && <a href={demo.instagramUrl} target="_blank" rel="noreferrer" aria-label="Instagram"><Camera /></a>}{demo.facebookUrl && <a href={demo.facebookUrl} target="_blank" rel="noreferrer" aria-label="Facebook">f</a>}{demo.email && <a href={`mailto:${demo.email}`} aria-label="Email"><Mail /></a>}</div><small className="footer-credits"><span>© {new Date().getFullYear()} {demo.businessName}. All rights reserved.</span><span>Designed &amp; Developed by <a href="https://www.sufiyanakhtar.com/" target="_blank" rel="noopener noreferrer">Sufiyan Akhtar</a></span></small></footer>
  </main>;
}
