"use client";
import Link from "next/link";
import { BadgeIndianRupee, CalendarClock, ChevronRight, CircleDollarSign, Clock3, QrCode, TrendingUp, UserCheck, UserMinus, Users } from "lucide-react";
import { Avatar, Badge, SectionTitle, StatCard } from "@/components/ui";
import { useToast } from "@/components/ui/toast-provider";
import { currency, membershipStatus, shortDate } from "@/lib/utils";
import type { Member, Payment } from "@/types";
import { memberships } from "@/data/mock";

const revenue = [180, 210, 230, 205, 260, 285]; const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];
export function DashboardView({ members, payments }: { members: Member[]; payments: Payment[] }) {
  const toast = useToast(); const expiring = members.filter((m) => membershipStatus(m.expiryDate) === "expiring");
  const stats = [["Total Members", "428", "+18 this month", <Users key="i" />, "lime"], ["Active Members", "347", "81% retention", <UserCheck key="i" />, "blue"], ["Expired", "39", "Needs follow-up", <UserMinus key="i" />, "orange"], ["Expiring Soon", "42", "Next 7 days", <CalendarClock key="i" />, "violet"], ["Pending Fees", "₹38,500", "23 members", <CircleDollarSign key="i" />, "orange"], ["Today's Attendance", "126", "+8% vs yesterday", <QrCode key="i" />, "blue"], ["Today's Collection", "₹18,500", "14 payments", <BadgeIndianRupee key="i" />, "lime"], ["Monthly Revenue", "₹2,84,750", "+12.4% vs July", <TrendingUp key="i" />, "violet"]] as const;
  return <><div className="page-heading"><div><span className="eyebrow">Command center</span><h1>Dashboard</h1><p>Here’s what’s happening at Golden Gym today.</p></div><div className="heading-actions"><button className="btn secondary" onClick={() => toast("Report exported successfully")}>Export report</button><Link className="btn primary" href="/attendance"><QrCode size={17} /> Scan attendance</Link></div></div>
    <div className="stat-grid">{stats.map(([label, value, detail, icon, tone]) => <StatCard key={label} label={label} value={value} detail={detail} icon={icon} tone={tone} />)}</div>
    <div className="dashboard-grid">
      <section className="panel revenue-panel"><SectionTitle title="Revenue overview" subtitle="Monthly collection in thousands" action={<select className="compact-select"><option>Last 6 months</option></select>} /><div className="bar-chart">{revenue.map((v, i) => <div className="bar-col" key={months[i]}><span className="bar-value">₹{v}K</span><div className="bar" style={{ height: `${(v / 300) * 180}px` }} /><small>{months[i]}</small></div>)}</div></section>
      <section className="panel"><SectionTitle title="Attendance overview" subtitle="This week" /><div className="line-chart"><svg viewBox="0 0 500 180" role="img" aria-label="Weekly attendance trend"><defs><linearGradient id="lineFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8ff3e" stopOpacity=".28"/><stop offset="1" stopColor="#d8ff3e" stopOpacity="0"/></linearGradient></defs><path d="M10 145 L90 110 L170 128 L250 72 L330 88 L410 35 L490 50 L490 180 L10 180Z" fill="url(#lineFill)"/><polyline points="10,145 90,110 170,128 250,72 330,88 410,35 490,50" fill="none" stroke="#b9e229" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{["M","T","W","T","F","S","S"].map((d,i)=><text key={i} x={10+i*80} y="176" fill="#8c939f" fontSize="13">{d}</text>)}</svg></div><div className="chart-summary"><div><strong>126</strong><span>Today</span></div><div><strong>108</strong><span>Daily avg.</span></div><div><strong>7–9 PM</strong><span>Peak time</span></div></div></section>
      <section className="panel wide"><SectionTitle title="Recent payments" subtitle="Latest member transactions" action={<Link className="text-link" href="/payments">View all <ChevronRight size={15}/></Link>} /><div className="table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Method</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.slice(0,6).map((p) => { const member=members.find(m=>m.id===p.memberId)!; return <tr key={p.id}><td><div className="person-cell"><Avatar src={member.image} name={member.name} size={36}/><div><b>{member.name}</b><small>{p.id}</small></div></div></td><td>{p.plan}</td><td>{p.method}</td><td>{shortDate(p.date)}</td><td><b>{currency(p.amount)}</b></td><td><Badge status={p.status}/></td></tr>})}</tbody></table></div></section>
      <section className="panel"><SectionTitle title="Membership mix" subtitle="Active member distribution" /><div className="donut-wrap"><div className="donut"><span><strong>428</strong>Total</span></div><div className="legend">{memberships.map((p,i)=><div key={p.id}><i style={{background:["#d8ff3e","#5e8cff","#9c6cff","#ff8a55"][i]}}/><span>{p.name}</span><b>{p.members}</b></div>)}</div></div></section>
      <section className="panel wide"><SectionTitle title="Expiring soon" subtitle="Reach out before memberships lapse" action={<Link className="text-link" href="/members">View members <ChevronRight size={15}/></Link>} /><div className="expiry-list">{expiring.slice(0,5).map((m)=><div className="expiry-item" key={m.id}><Avatar src={m.image} name={m.name}/><div><b>{m.name}</b><span>{memberships.find(p=>p.id===m.planId)?.name} plan</span></div><div className="expiry-date"><Clock3 size={15}/><span>{shortDate(m.expiryDate)}</span></div><Link className="btn tiny secondary" href={`/members/${m.id}`}>View</Link><button className="btn tiny primary" onClick={()=>toast("Reminder simulated successfully. WhatsApp/SMS API will be connected later.")}>Send reminder</button></div>)}</div></section>
    </div></>;
}
