import Link from "next/link";
import { notFound } from "next/navigation";
import { Activity, ArrowLeft, CalendarCheck, Dumbbell, Mail, Phone, Scale, Utensils, WalletCards } from "lucide-react";
import { Avatar, Badge, SectionTitle, StatCard } from "@/components/ui";
import { currency, membershipStatus, shortDate } from "@/lib/utils";
import { getMemberById, getMemberships, getPayments, getTrainers } from "@/services";

export default async function MemberProfile({params}:{params:Promise<{id:string}>}){const {id}=await params; const [member,plans,trainers,payments]=await Promise.all([getMemberById(id),getMemberships(),getTrainers(),getPayments()]); if(!member)notFound(); const plan=plans.find(p=>p.id===member.planId)!; const trainer=trainers.find(t=>t.id===member.trainerId); const status=membershipStatus(member.expiryDate); const days=status==="expired"?0:status==="expiring"?5:42;
return <><div className="profile-back"><Link href="/members"><ArrowLeft size={17}/> Back to members</Link></div><section className="profile-hero"><div className="profile-person"><Avatar src={member.image} name={member.name} size={112}/><div><Badge status={status}/><h1>{member.name}</h1><p>{member.memberId} · Member since {new Date(member.joinedAt).getFullYear()}</p><div className="contact-row"><span><Phone size={15}/>{member.phone}</span><span><Mail size={15}/>{member.email}</span></div></div></div><div className="heading-actions"><button className="btn secondary">Edit profile</button><button className="btn primary">Renew membership</button></div></section>
<div className="profile-stat-grid"><StatCard label="Current plan" value={plan.name} detail={`Expires ${shortDate(member.expiryDate)}`} icon={<WalletCards/>}/><StatCard label="Days remaining" value={String(days)} detail={status==="expiring"?"Renewal recommended":"Membership healthy"} icon={<CalendarCheck/>} tone="orange"/><StatCard label="This month" value={`${member.attendance} visits`} detail="5 day streak" icon={<Activity/>} tone="blue"/><StatCard label="Progress" value={`${member.startWeight-member.weight} kg lost`} detail={`Goal: ${member.goalWeight} kg`} icon={<Scale/>} tone="violet"/></div>
<div className="profile-grid"><section className="panel"><SectionTitle title="Personal information"/><dl className="info-grid"><div><dt>Gender</dt><dd>{member.gender}</dd></div><div><dt>Date of birth</dt><dd>{shortDate(member.dob)}</dd></div><div><dt>Joining date</dt><dd>{shortDate(member.joinedAt)}</dd></div><div><dt>Emergency contact</dt><dd>{member.emergencyContact}</dd></div><div><dt>Membership start</dt><dd>{shortDate(member.startDate)}</dd></div><div><dt>Payment status</dt><dd><Badge status={member.paymentStatus}/></dd></div></dl></section>
<section className="panel trainer-mini"><SectionTitle title="Assigned trainer"/>{trainer&&<><Avatar src={trainer.image} name={trainer.name} size={74}/><h3>{trainer.name}</h3><p>{trainer.specialization}</p><span>{trainer.phone}</span><Link href={`/trainers/${trainer.id}`} className="btn secondary full">View trainer profile</Link></>}</section>
<section className="panel wide"><SectionTitle title="Body progress" subtitle="Last 6 monthly check-ins"/><div className="progress-chart"><svg viewBox="0 0 700 210"><path d="M20 40 L150 66 L280 98 L410 116 L540 148 L680 166" fill="none" stroke="#d8ff3e" strokeWidth="4"/><path d="M20 40 L150 66 L280 98 L410 116 L540 148 L680 166 L680 200 L20 200Z" fill="rgba(216,255,62,.08)"/>{[20,150,280,410,540,680].map((x,i)=><circle key={x} cx={x} cy={[40,66,98,116,148,166][i]} r="6" fill="#151812" stroke="#d8ff3e" strokeWidth="3"/>)}</svg></div><div className="measurement-row">{[["Weight",`${member.weight} kg`],["BMI","23.1"],["Body fat","18.4%"],["Chest","101 cm"],["Waist","84 cm"],["Arms","37 cm"]].map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</div></section>
<section className="panel"><SectionTitle title="Today’s workout" action={<Dumbbell size={19}/>}/><div className="plan-list">{[["Bench Press","4 × 10"],["Incline Dumbbell Press","3 × 12"],["Cable Fly","3 × 15"],["Tricep Pushdown","3 × 12"]].map(([n,r],i)=><div key={n}><i>{i+1}</i><span><b>{n}</b><small>{r}</small></span></div>)}</div></section>
<section className="panel"><SectionTitle title="Today’s diet" action={<Utensils size={19}/>}/><div className="meal-list">{[["08:00","Oats, eggs & green tea"],["11:00","Fruit & buttermilk"],["13:30","Rice, paneer & salad"],["20:00","Chicken, vegetables & soup"]].map(([t,m])=><div key={t}><time>{t}</time><span>{m}</span></div>)}</div></section>
<section className="panel wide"><SectionTitle title="Payment history"/><div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Plan</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.filter(p=>p.memberId===member.id).map(p=><tr key={p.id}><td>{p.id}</td><td>{shortDate(p.date)}</td><td>{p.plan}</td><td>{p.method}</td><td>{currency(p.amount)}</td><td><Badge status={p.status}/></td></tr>)}</tbody></table></div></section>
</div></>}
