"use client";
import Link from "next/link";
import { Camera, Eye, EyeOff, Plus, Search, SlidersHorizontal, Upload, UserPlus } from "lucide-react";
import { useMemo, useState } from "react";
import { Avatar, Badge, EmptyState } from "@/components/ui";
import { Modal } from "@/components/ui/modal";
import { useToast } from "@/components/ui/toast-provider";
import { saveMemberWebsiteOverride, useMemberWebsiteOverrides } from "@/lib/member-showcase";
import { currency, membershipStatus, shortDate } from "@/lib/utils";
import type { Member, Membership, Trainer } from "@/types";

export function MembersView({ initialMembers, plans, trainers }: { initialMembers: Member[]; plans: Membership[]; trainers: Trainer[] }) {
  const [localMembers, setLocalMembers] = useState(initialMembers);
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [addOpen,setAddOpen]=useState(false);
  const [photoMember,setPhotoMember]=useState<Member|null>(null); const [photoPreview,setPhotoPreview]=useState(""); const toast=useToast();
  const overrides=useMemberWebsiteOverrides();
  const members=localMembers.map(member=>({...member,...overrides[member.id]}));
  const filtered=useMemo(()=>members.filter(m=>{const matches=`${m.name} ${m.phone} ${m.memberId}`.toLowerCase().includes(query.toLowerCase()); const status=membershipStatus(m.expiryDate); return matches&&(filter==="all"||filter===status||(filter==="pending"&&m.paymentStatus==="pending"));}),[members,query,filter]);

  function addMember(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const name=String(form.get("name"));setLocalMembers([{...localMembers[0],id:`local-${Date.now()}`,memberId:`GG-${1100+localMembers.length}`,name,phone:String(form.get("phone")),email:String(form.get("email")),image:"",showOnWebsite:false,planId:String(form.get("plan")),expiryDate:new Date(Date.now()+90*86400000).toISOString().slice(0,10)},...localMembers]);setAddOpen(false);toast("Member added to this demo session successfully");}
  function toggleWebsite(member:Member){saveMemberWebsiteOverride(member.id,{showOnWebsite:!member.showOnWebsite});toast(member.showOnWebsite?`${member.name} hidden from public website`:`${member.name} is now visible on public website`);}
  function selectPhoto(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){toast("Please select a JPG, PNG or WebP image");return}if(file.size>1_500_000){toast("Image must be smaller than 1.5 MB for this demo");return}const reader=new FileReader();reader.onload=()=>setPhotoPreview(String(reader.result));reader.readAsDataURL(file);}
  function savePhoto(){if(!photoMember||!photoPreview)return;saveMemberWebsiteOverride(photoMember.id,{image:photoPreview});setPhotoMember(null);setPhotoPreview("");toast("Member photo updated and ready for the website");}

  return <><div className="page-heading"><div><span className="eyebrow">People</span><h1>Members</h1><p>Manage profiles, memberships, fees and public website visibility.</p></div><button className="btn primary" onClick={()=>setAddOpen(true)}><UserPlus size={17}/> Add member</button></div>
  <div className="filter-row"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or member ID"/></label><div className="filter-tabs">{[["all","All"],["active","Active"],["expiring","Expiring"],["expired","Expired"],["pending","Payment pending"]].map(([v,l])=><button className={filter===v?"active":""} onClick={()=>setFilter(v)} key={v}>{l}</button>)}</div><button className="btn icon-only secondary"><SlidersHorizontal size={18}/></button></div>
  <section className="panel table-panel">{filtered.length?<div className="table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Expiry</th><th>Trainer</th><th>Fees</th><th>Status</th><th>Website</th><th>Photo</th></tr></thead><tbody>{filtered.map(m=>{const status=membershipStatus(m.expiryDate);const trainer=trainers.find(t=>t.id===m.trainerId);return <tr key={m.id}><td><Link href={`/members/${m.id}`} className="person-cell"><Avatar src={m.image} name={m.name}/><div><b>{m.name}</b><small>{m.memberId} · {m.phone}</small></div></Link></td><td>{plans.find(p=>p.id===m.planId)?.name}</td><td>{shortDate(m.expiryDate)}</td><td>{trainer?.name??"Unassigned"}</td><td><b className={m.fees?"text-danger":""}>{m.fees?currency(m.fees):"Cleared"}</b></td><td><Badge status={status}/></td><td><button className={`website-toggle ${m.showOnWebsite?"visible":""}`} onClick={()=>toggleWebsite(m)}>{m.showOnWebsite?<><Eye size={15}/>Shown</>:<><EyeOff size={15}/>Hidden</>}</button></td><td><button className="icon-btn" title="Upload member photo" onClick={()=>{setPhotoMember(m);setPhotoPreview(m.image)}}><Camera size={17}/></button></td></tr>})}</tbody></table></div>:<EmptyState title="No members found" text="Try changing your search or status filter."/>}</section>
  <Modal open={addOpen} onClose={()=>setAddOpen(false)} title="Add a new member"><form className="form-grid" onSubmit={addMember}><label>Full name<input name="name" required placeholder="e.g. Aarav Shah"/></label><label>Phone<input name="phone" required pattern="[0-9]{10}" placeholder="10-digit number"/></label><label>Email<input name="email" type="email" required placeholder="member@example.com"/></label><label>Membership plan<select name="plan">{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {currency(p.price)}</option>)}</select></label><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setAddOpen(false)}>Cancel</button><button className="btn primary"><Plus size={17}/> Add member</button></div></form></Modal>
  <Modal open={Boolean(photoMember)} onClose={()=>{setPhotoMember(null);setPhotoPreview("")}} title="Update member photo"><div className="photo-upload"><Avatar src={photoPreview||photoMember?.image} name={photoMember?.name??"Member"} size={140}/><div><h3>{photoMember?.name}</h3><p>This photo will be used on the member profile and public website when visibility is enabled.</p><label className="btn secondary"><Upload size={16}/>Choose image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={selectPhoto}/></label><small>JPG, PNG or WebP · Maximum 1.5 MB</small></div></div><div className="modal-actions"><button className="btn secondary" onClick={()=>{setPhotoMember(null);setPhotoPreview("")}}>Cancel</button><button className="btn primary" disabled={!photoPreview} onClick={savePhoto}>Save photo</button></div></Modal></>;
}
