"use client";
import { useState } from "react";
import { CheckCircle2, QrCode, ScanLine, UserCheck } from "lucide-react";
import { Avatar, Badge, SectionTitle, StatCard } from "@/components/ui";
import { membershipStatus, shortDate } from "@/lib/utils";
import type { Attendance, Member, Trainer } from "@/types";
import { memberships } from "@/data/mock";

export function AttendanceView({members,records,trainers}:{members:Member[];records:Attendance[];trainers:Trainer[]}){const [selected,setSelected]=useState(members[0]); const status=membershipStatus(selected.expiryDate); const trainer=trainers.find(t=>t.id===selected.trainerId);
return <><div className="page-heading"><div><span className="eyebrow">Smart check-in</span><h1>QR Attendance</h1><p>Fast, contactless attendance with manual fallback.</p></div><button className="btn secondary"><UserCheck size={17}/> Manual entry</button></div><div className="attendance-layout"><section className="scan-card"><div className="scan-corners"><QrCode size={116}/></div><span className="eyebrow">Ready to scan</span><h2>Scan QR to Mark Attendance</h2><p>Place the member QR code inside the frame</p><div className="or"><span/>OR<span/></div><label>Select demo member<select value={selected.id} onChange={e=>setSelected(members.find(m=>m.id===e.target.value)!)}>{members.map(m=><option value={m.id} key={m.id}>{m.name} · {m.memberId}</option>)}</select></label></section>
<section className={`welcome-card ${status}`}><div className="scan-status"><ScanLine size={20}/><span>SCAN RESULT</span></div><Avatar src={selected.image} name={selected.name} size={92}/><h2>{status==="expired"?"Membership Expired":`Welcome, ${selected.name.split(" ")[0]}!`}</h2><p>{status==="expired"?"Please contact reception for renewal.":"Attendance marked successfully"}</p><div className="welcome-info"><div><span>Membership</span><Badge status={status}/></div><div><span>Plan</span><b>{memberships.find(p=>p.id===selected.planId)?.name}</b></div><div><span>Expires</span><b>{shortDate(selected.expiryDate)}</b></div><div><span>Pending payment</span><b>₹{selected.fees.toLocaleString("en-IN")}</b></div><div><span>Trainer</span><b>{trainer?.name}</b></div></div>{status!=="expired"&&<div className="success-line"><CheckCircle2 size={18}/> Checked in at 07:42 AM</div>}</section></div>
<div className="stat-grid compact"><StatCard label="Today’s check-ins" value="126" detail="Peak 7–9 AM" icon={<UserCheck/>}/><StatCard label="Currently inside" value="48" detail="Capacity 200" icon={<ScanLine/>} tone="blue"/><StatCard label="Avg. visit duration" value="74 min" detail="This week" icon={<QrCode/>} tone="violet"/></div>
<section className="panel table-panel"><SectionTitle title="Recent attendance" subtitle="Live check-in activity"/><div className="table-wrap"><table><thead><tr><th>Member</th><th>Check-in</th><th>Date</th><th>Status</th><th>Trainer</th><th>Check-out</th></tr></thead><tbody>{records.map(r=>{const m=members.find(x=>x.id===r.memberId)!;return <tr key={r.id}><td><div className="person-cell"><Avatar src={m.image} name={m.name}/><div><b>{m.name}</b><small>{m.memberId}</small></div></div></td><td>{r.checkIn}</td><td>{shortDate(r.date)}</td><td><Badge status={membershipStatus(m.expiryDate)}/></td><td>{r.trainer}</td><td>{r.checkOut}</td></tr>})}</tbody></table></div></section></>}
